'use client'
import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import { Provider } from 'react-redux';
import store from '../redux/store';
import Navbar from "../components/NavBar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-poppins', 
});

const metadata: Metadata = {
  title: "FindingFura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
        <Provider store={store}> 
          <Navbar />
          {children}
          <Footer />
    </Provider>
        </body>
      </html>
  );
}
